name: On Branch Push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Testing stuff
      shell: pwsh
      run: |
        $version=(git rev-parse --short HEAD)
        dotnet publish -c Release -o Muscurdi_bin -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe -p:SourceRevisionId=$version -p:RuntimeIdentifier=linux-x64
        Compress-Archive "Muscurdi_bin" "Muscurdi_win.zip" && ls
      working-directory: Muscurdi

    # - name: run tests
    #   run: dotnet test