name: On Release Published

on:
  release:
    types: [published]

jobs:
  publish-binaries:
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    
    - name: Creating Bin folder
      run: mkdir bin_release

# Might want to use Matrix here
    - name: Build Binary Linux
      shell: pwsh
      run: |
        $version=(git rev-parse --short HEAD)
        dotnet publish -c Release -o Muscurdi_bin -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe -p:SourceRevisionId=$version -p:RuntimeIdentifier=linux-x64
      working-directory: Muscurdi
    
    - name: Zip Binary
      shell: pwsh
      run: Compress-Archive "Muscurdi_bin" "Muscurdi_linux.zip" && mv Muscurdi_linux.zip ../bin_release && rm -r Muscurdi_bin/
      working-directory: Muscurdi
    
    - name: Build Binary Win
      shell: pwsh
      run: |
        $version=(git rev-parse --short HEAD)
        dotnet publish -c Release -o Muscurdi_bin -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe -p:SourceRevisionId=$version -p:RuntimeIdentifier=win-x64
      working-directory: Muscurdi
    
    - name: Zip Binary
      shell: pwsh
      run: Compress-Archive "Muscurdi_bin" "Muscurdi_win.zip" && mv Muscurdi_win.zip ../bin_release && rm -r Muscurdi_bin/
      working-directory: Muscurdi

    - name: Build Binary MacOS
      shell: pwsh
      run: |
        $version=(git rev-parse --short HEAD)
        dotnet publish -c Release -o Muscurdi_bin -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe -p:SourceRevisionId=$version -p:RuntimeIdentifier=osx-x64
      working-directory: Muscurdi
    
    - name: Zip Binary
      shell: pwsh
      run: Compress-Archive "Muscurdi_bin" "Muscurdi_osx.zip" && mv Muscurdi_osx.zip ../bin_release  && rm -r Muscurdi_bin/
      working-directory: Muscurdi

    - name: Upload Bin Linux
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'bin_release/Muscurdi_linux.zip'

    - name: Upload Bin Win
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'bin_release/Muscurdi_win.zip'

    - name: Upload Bin Mac
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'bin_release/Muscurdi_osx.zip'
