name: On Release Published

on:
  release:
    types: [published]

jobs:
  build-publish:
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    
    - name: Creating Bin folder
      run: mkdir bin_release
    
    - name: Build Binary Linux
      run: dotnet publish -c Release -o publish -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:RuntimeIdentifier=linux-x64 -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe
      working-directory: Muscurdi
    
    - name: Zip Binary
      run: tar -cvzf "linux_bin.zip" "publish" && mv linux_bin.zip ../bin_release 
      working-directory: Muscurdi
    
    - name: Check Files
      run: ls bin_release 